// src/components/PasswordVerifyDialog.vue
<!-- 密码验证对话框 — 从 src-legacy/components/PasswordVerifyDialog.tsx 原样移植
     （文案逐字保留）。编辑连接时查看已存明文密码前的门禁，挂在 ConnectionDialog 内。
     成功后把输入的主密码回传给父组件（success 事件）；父组件负责原子揭示。
     旧版样式沿用：本地遮罩（点遮罩不关闭，与旧版一致），z-index 3000 压过编辑框。 -->
<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import type { ComponentPublicInstance } from "vue";
import { Lock } from "@element-plus/icons-vue";
import { MyButton, MyInput } from "myui";
import { verifyPassword } from "@/api";

defineOptions({ name: "PasswordVerifyDialog" });

const emit = defineEmits<{
  /** 内联预检通过后回传明文主密码。
   *  后端在解密时会权威地再验一次（原子揭示）——本对话框的检查只是 UX
   *  （内联错误、防呆），不是安全边界。 */
  success: [masterPassword: string];
  close: [];
}>();

const MIN_LEN = 6;

const pass = ref("");
const busy = ref(false);
const err = ref<string | null>(null);
// MyInput 根节点（.my-field），内层原生 input 挂载后手动聚焦（对齐旧 useEffect）
const inputRef = ref<ComponentPublicInstance | null>(null);

onMounted(() => {
  const el = inputRef.value?.$el as HTMLElement | undefined;
  el?.querySelector("input")?.focus();
});

const canSubmit = computed(() => pass.value.length >= MIN_LEN && !busy.value);

async function submit(): Promise<void> {
  if (!canSubmit.value) return;
  busy.value = true;
  err.value = null;
  try {
    const valid = await verifyPassword(pass.value);
    if (valid) {
      const typed = pass.value;
      pass.value = "";
      emit("success", typed);
    } else {
      err.value = "密码错误";
      pass.value = "";
    }
  } catch (e) {
    err.value = String(e);
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <div class="overlay">
    <div class="panel" @click.stop>
      <div class="title">
        <el-icon class="title-icon" :size="14"><Lock /></el-icon>
        验证密码
      </div>
      <div class="subtitle">请输入登录密码以查看明文密码</div>

      <label class="field-label">登录密码</label>
      <MyInput
        ref="inputRef"
        v-model="pass"
        :clearable="false"
        type="password"
        placeholder="输入登录密码"
        @keydown.enter="submit"
      />

      <div v-if="err" class="error-box">{{ err }}</div>

      <div class="actions">
        <MyButton variant="secondary" size="small" @click="emit('close')">取消</MyButton>
        <MyButton variant="primary" size="small" :disabled="!canSubmit" @click="submit">
          {{ busy ? "验证中…" : "确认" }}
        </MyButton>
      </div>
    </div>
  </div>
</template>

<style scoped>
.overlay {
  position: fixed;
  inset: 0;
  background: var(--bg-overlay);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 3000;
}

.panel {
  background: var(--bg-elevated);
  border: 1px solid var(--border-default);
  border-radius: var(--radius-md);
  padding: 20px;
  width: 360px;
  box-shadow: var(--shadow-xl);
}

.title {
  font-size: 14px;
  font-weight: 600;
  margin-bottom: 6px;
  color: var(--text-primary);
  display: flex;
  align-items: center;
  gap: 5px;
}

.title-icon {
  color: var(--text-secondary);
}

.subtitle {
  font-size: 12px;
  color: var(--text-muted);
  margin-bottom: 14px;
}

.field-label {
  display: block;
  font-size: 11px;
  color: var(--text-muted);
  margin-bottom: 4px;
}

.error-box {
  margin-top: 10px;
  padding: 8px 10px;
  background: var(--error-muted);
  border: 1px solid var(--error);
  border-radius: var(--radius-sm);
  font-size: 12px;
  color: var(--error);
}

.actions {
  display: flex;
  gap: 8px;
  margin-top: 16px;
  justify-content: flex-end;
}
</style>

// src/components/PasswordVerifyDialog.tsx
import { useState, useRef, useEffect } from "react";
import { verifyPassword } from "../api";

interface Props {
  onSuccess: () => void;
  onClose: () => void;
}

const MIN_LEN = 6;

export function PasswordVerifyDialog({ onSuccess, onClose }: Props) {
  const [pass, setPass] = useState("");
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const canSubmit = pass.length >= MIN_LEN && !busy;

  async function submit() {
    if (!canSubmit) return;
    setBusy(true);
    setErr(null);
    try {
      const valid = await verifyPassword(pass);
      if (valid) {
        setPass("");
        onSuccess();
      } else {
        setErr("密码错误");
        setPass("");
      }
    } catch (e) {
      setErr(String(e));
    } finally {
      setBusy(false);
    }
  }

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.55)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 3000,
      }}
      onClick={onClose}
    >
      <div
        onClick={(e) => e.stopPropagation()}
        style={{
          background: "var(--bg-panel)",
          border: "1px solid var(--border)",
          borderRadius: 10,
          padding: 20,
          width: 360,
          boxShadow: "0 12px 36px rgba(0,0,0,0.5)",
        }}
      >
        <div style={{ fontSize: 14, fontWeight: 600, marginBottom: 6 }}>
          🔐 验证密码
        </div>
        <div style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 14 }}>
          请输入登录密码以查看明文密码
        </div>

        <label style={labelStyle}>登录密码</label>
        <input
          ref={inputRef}
          type="password"
          value={pass}
          onChange={(e) => setPass(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") submit();
          }}
          placeholder="输入登录密码"
          style={inputStyle}
        />

        {err && (
          <div style={errorBoxStyle}>{err}</div>
        )}

        <div style={{ display: "flex", gap: 8, marginTop: 16, justifyContent: "flex-end" }}>
          <button onClick={onClose} style={cancelBtnStyle}>
            取消
          </button>
          <button
            onClick={submit}
            disabled={!canSubmit}
            style={{
              ...primaryBtnStyle,
              opacity: canSubmit ? 1 : 0.45,
              cursor: canSubmit ? "pointer" : "not-allowed",
            }}
          >
            {busy ? "验证中…" : "确认"}
          </button>
        </div>
      </div>
    </div>
  );
}

const labelStyle: React.CSSProperties = {
  display: "block",
  fontSize: 11,
  color: "var(--text-muted)",
  marginBottom: 4,
};

const inputStyle: React.CSSProperties = {
  width: "100%",
  boxSizing: "border-box",
  padding: "10px 12px",
  background: "var(--bg-input)",
  color: "var(--text-primary)",
  border: "1px solid var(--border)",
  borderRadius: 6,
  fontSize: 13,
  outline: "none",
};

const errorBoxStyle: React.CSSProperties = {
  marginTop: 10,
  padding: "8px 10px",
  background: "rgba(239,93,111,0.12)",
  border: "1px solid var(--error)",
  borderRadius: 6,
  fontSize: 12,
  color: "var(--error)",
};

const primaryBtnStyle: React.CSSProperties = {
  padding: "8px 16px",
  background: "var(--accent)",
  color: "var(--bg-panel)",
  border: "none",
  borderRadius: 6,
  fontSize: 12,
  fontWeight: 600,
};

const cancelBtnStyle: React.CSSProperties = {
  padding: "7px 14px",
  background: "transparent",
  color: "var(--text-secondary)",
  border: "1px solid var(--border)",
  borderRadius: 6,
  fontSize: 12,
  cursor: "pointer",
};
