// src/components/UpdateNotification.vue
<!-- 更新可用浮层卡片（自包含）。
     从 src-legacy/components/UpdateNotification.tsx 原样移植：
     updateInfo 改从 @/composables/useUpdateCheck 读取（旧版经 prop 传入，渲染条件
     updateInfo.has_update 收进本组件 visible），忽略/下载/安装/浏览器跳转逻辑照旧。
     位置按迁移指令与旧 App.tsx 设计注释（"show the bottom-left UpdateNotification card,
     dismissable, per-version"）实现为左下角浮层卡片，替代全屏居中遮罩；
     忽略后按版本号记忆（localStorage myshell.ignoredUpdateVersion），新版本重新弹出。
     两条路径：Windows 走应用内下载+安装（进度条→安装并重启）；
     Linux/macOS（update_strategy="browser"）只提供"打开下载页"。 -->
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, watch } from "vue";
import type { UnlistenFn } from "@tauri-apps/api/event";
import { Bell } from "@element-plus/icons-vue";
import { MyButton } from "myui";
import {
  downloadUpdate,
  installUpdate,
  onUpdateDownloadProgress,
  openExternalUrl,
} from "@/api";
import { updateInfo } from "@/composables/useUpdateCheck";

defineOptions({ name: "UpdateNotification" });

type Phase = "prompt" | "downloading" | "ready" | "failed";

const latest = computed(() => updateInfo.value?.latest_version ?? "");
// latest_version comes from the Gitee tag which already includes "v" (e.g.
// "v1.6.1"). Display it as-is to avoid a double "v" prefix.
const latestDisplay = computed(() => {
  const v = latest.value;
  return v.startsWith("v") ? v : `v${v}`;
});
// Linux/macOS path: no built-in installer-launch pipeline. Skip the
// download+install phases and offer a single button that opens the
// release page in the system browser (user downloads the .deb/.dmg
// manually). Windows keeps the original auto-download flow.
const isBrowserMode = computed(() => updateInfo.value?.update_strategy === "browser");

const downloadUrl = computed(() => updateInfo.value?.download_url || updateInfo.value?.release_url || "");

const IGNORE_KEY = "myshell.ignoredUpdateVersion";
// 旧版 useState 惰性初始化 → IIFE 求值一次（等价语义）
const ignored = ref<boolean>(
  (() => {
    try {
      return localStorage.getItem(IGNORE_KEY) === latest.value;
    } catch {
      return false;
    }
  })(),
);

watch(latest, (v) => {
  try {
    if (localStorage.getItem(IGNORE_KEY) !== v) ignored.value = false;
  } catch {
    // ignore
  }
});

const visible = computed(() => !!updateInfo.value?.has_update && !ignored.value);

const phase = ref<Phase>("prompt");
const progress = ref<{ downloaded: number; total: number }>({
  downloaded: 0,
  total: 0,
});
const error = ref<string>("");
const downloadedPath = ref<string>("");

// 旧版 useEffect([phase])：进入 downloading 才订阅下载进度事件（token 防竞态）。
let progressSub: UnlistenFn | null = null;
let progressToken = 0;

watch(phase, (p) => {
  const token = ++progressToken;
  progressSub?.();
  progressSub = null;
  if (p !== "downloading") return;
  void onUpdateDownloadProgress((evt) => {
    progress.value = { downloaded: evt.downloaded, total: evt.total };
  }).then((fn) => {
    if (token !== progressToken) fn();
    else progressSub = fn;
  });
});

onBeforeUnmount(() => {
  progressToken++;
  progressSub?.();
  progressSub = null;
});

const pct = computed(() =>
  progress.value.total > 0
    ? Math.min(100, Math.round((progress.value.downloaded / progress.value.total) * 100))
    : null,
);

async function handleUpdate(): Promise<void> {
  phase.value = "downloading";
  progress.value = { downloaded: 0, total: 0 };
  error.value = "";
  try {
    const path = await downloadUpdate(downloadUrl.value);
    downloadedPath.value = path;
    phase.value = "ready";
  } catch (e) {
    error.value = String(e);
    phase.value = "failed";
  }
}

async function handleInstall(): Promise<void> {
  if (!downloadedPath.value) {
    error.value = "安装包路径丢失";
    phase.value = "failed";
    return;
  }
  try {
    await installUpdate(downloadedPath.value);
  } catch (e) {
    error.value = String(e);
    phase.value = "failed";
  }
}

function handleIgnore(): void {
  ignored.value = true;
  try {
    localStorage.setItem(IGNORE_KEY, latest.value);
  } catch {
    // best-effort
  }
}

function openBrowser(): void {
  if (downloadUrl.value) void openExternalUrl(downloadUrl.value);
}
</script>

<template>
  <div v-if="visible" class="update-card animate-scale-in">
    <!-- Header -->
    <div class="header">
      <div class="icon-circle">
        <span class="icon">
          <el-icon :size="22"><Bell /></el-icon>
        </span>
      </div>
      <div class="title">MyShell 有新版本可用</div>
      <div class="version">{{ latestDisplay }}</div>
    </div>

    <!-- Subtitle / status -->
    <div class="subtitle">
      <template v-if="phase === 'prompt'">
        {{
          isBrowserMode
            ? "检测到新版本。当前系统暂不支持应用内自动更新，请前往下载页手动下载安装。"
            : "新版本已就绪，是否立即更新？"
        }}
      </template>
      <template v-else-if="phase === 'downloading'">
        {{ pct !== null ? `正在下载… ${pct}%` : "正在下载…" }}
      </template>
      <template v-else-if="phase === 'ready'">下载完成，点击安装并重启应用</template>
      <template v-else>{{ error || "下载出现问题" }}</template>
    </div>

    <!-- Progress bar -->
    <div v-if="phase === 'downloading'" class="progress-track">
      <div class="progress-fill" :style="{ width: pct !== null ? `${pct}%` : '0%' }"></div>
    </div>

    <!-- Actions -->
    <div class="actions">
      <template v-if="phase === 'prompt'">
        <MyButton variant="ghost" class="grow" @click="handleIgnore">忽略</MyButton>
        <MyButton v-if="isBrowserMode" variant="primary" class="grow" @click="openBrowser">
          打开下载页
        </MyButton>
        <MyButton v-else variant="primary" class="grow" @click="handleUpdate">更新</MyButton>
      </template>
      <div v-else-if="phase === 'downloading'" class="downloading-text">
        请稍候，下载完成后将自动提示…
      </div>
      <template v-else-if="phase === 'ready'">
        <MyButton variant="primary" class="grow full" @click="handleInstall">安装并重启</MyButton>
      </template>
      <template v-else>
        <MyButton variant="primary" class="grow" @click="openBrowser">浏览器下载</MyButton>
        <MyButton variant="ghost" class="grow" @click="handleUpdate">重试</MyButton>
      </template>
    </div>
  </div>
</template>

<style scoped>
/* 旧版 global.css 的 animate-scale-in 在新版基样式中不存在，本地补齐 */
@keyframes scale-in {
  from {
    opacity: 0;
    transform: scale(0.96);
  }
  to {
    opacity: 1;
    transform: scale(1);
  }
}

.animate-scale-in {
  animation: scale-in var(--duration-normal) var(--ease-out-back);
}

/* 左下角浮层卡片（按旧 App.tsx 设计注释与迁移指令；旧实现为全屏遮罩，
   位置变化不影响交互语义：无遮罩、不阻塞主界面、按版本可忽略） */
.update-card {
  position: fixed;
  left: 16px;
  bottom: calc(var(--ui-statusbar-h) + 16px);
  z-index: 1500;
  width: 400px;
  max-width: 90vw;
  background: var(--bg-elevated);
  border: 1px solid var(--border-emphasis);
  border-radius: var(--radius-xl);
  box-shadow: var(--shadow-xl);
  overflow: hidden;
}

.header {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 28px 24px 0;
  gap: 10px;
}

.icon-circle {
  width: 48px;
  height: 48px;
  border-radius: var(--radius-full);
  background: var(--accent-primary-muted);
  border: 1px solid var(--border-subtle);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--accent-primary);
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.08);
}

.icon {
  font-size: 22px;
}

.title {
  font-size: 17px;
  font-weight: 600;
  color: var(--text-primary);
  letter-spacing: -0.01em;
}

.version {
  font-size: 13px;
  font-weight: 500;
  color: var(--accent-primary);
  background: var(--accent-primary-muted);
  padding: 3px 12px;
  border-radius: var(--radius-full);
  letter-spacing: 0.02em;
}

.subtitle {
  text-align: center;
  font-size: 13px;
  color: var(--text-tertiary);
  line-height: 1.5;
  padding: 14px 24px 0;
}

.progress-track {
  height: 3px;
  background: var(--bg-surface);
  margin: 14px 24px 0;
  border-radius: var(--radius-full);
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: var(--accent-primary);
  border-radius: var(--radius-full);
  transition: width 150ms cubic-bezier(0.32, 0.72, 0, 1);
}

.actions {
  display: flex;
  gap: 10px;
  padding: 20px 24px 24px;
}

.actions .grow {
  flex: 1;
}

.actions .full {
  width: 100%;
}

.downloading-text {
  flex: 1;
  text-align: center;
  font-size: 12px;
  color: var(--text-muted);
  padding: 8px 0;
}
</style>

// src/components/UpdateNotification.tsx
import { useEffect, useState } from "react";
import type { UnlistenFn } from "@tauri-apps/api/event";
import {
  downloadUpdate,
  installUpdate,
  onUpdateDownloadProgress,
  openExternalUrl,
  type UpdateInfo,
} from "../api";

interface Props {
  updateInfo: UpdateInfo;
}

type Phase = "prompt" | "downloading" | "ready" | "failed";

/**
 * Centered modal update dialog.
 *
 * Shown once after login when the background check detects a newer version.
 * Two actions:
 *   - "更新" → auto-download the installer → progress bar → "安装并重启"
 *   - "忽略" → remember this version in localStorage; never prompt
 *     again for the same version. A newer version will re-trigger the dialog.
 */
export function UpdateNotification({ updateInfo }: Props) {
  const latest = updateInfo.latest_version;
  const downloadUrl = updateInfo.download_url || updateInfo.release_url || "";
  // latest_version comes from the Gitee tag which already includes "v" (e.g.
  // "v1.6.1"). Display it as-is to avoid a double "v" prefix.
  const latestDisplay = latest.startsWith("v") ? latest : `v${latest}`;
  // Linux/macOS path: no built-in installer-launch pipeline. Skip the
  // download+install phases and offer a single button that opens the
  // release page in the system browser (user downloads the .deb/.dmg
  // manually). Windows keeps the original auto-download flow.
  const isBrowserMode = updateInfo.update_strategy === "browser";

  const IGNORE_KEY = "myshell.ignoredUpdateVersion";
  const [ignored, setIgnored] = useState<boolean>(() => {
    try {
      return localStorage.getItem(IGNORE_KEY) === latest;
    } catch {
      return false;
    }
  });

  useEffect(() => {
    try {
      if (localStorage.getItem(IGNORE_KEY) !== latest) setIgnored(false);
    } catch {
      // ignore
    }
  }, [latest]);

  const [phase, setPhase] = useState<Phase>("prompt");
  const [progress, setProgress] = useState<{ downloaded: number; total: number }>({
    downloaded: 0,
    total: 0,
  });
  const [error, setError] = useState<string>("");
  const [downloadedPath, setDownloadedPath] = useState<string>("");

  useEffect(() => {
    if (phase !== "downloading") return;
    let unlisten: UnlistenFn | null = null;
    let cancelled = false;
    onUpdateDownloadProgress((p) => {
      setProgress({ downloaded: p.downloaded, total: p.total });
    }).then((fn) => {
      if (cancelled) fn();
      else unlisten = fn;
    });
    return () => {
      cancelled = true;
      unlisten?.();
    };
  }, [phase]);

  if (ignored) return null;

  const handleUpdate = async () => {
    setPhase("downloading");
    setProgress({ downloaded: 0, total: 0 });
    setError("");
    try {
      const path = await downloadUpdate(downloadUrl);
      setDownloadedPath(path);
      setPhase("ready");
    } catch (e) {
      setError(String(e));
      setPhase("failed");
    }
  };

  const handleInstall = async () => {
    if (!downloadedPath) {
      setError("安装包路径丢失");
      setPhase("failed");
      return;
    }
    try {
      await installUpdate(downloadedPath);
    } catch (e) {
      setError(String(e));
      setPhase("failed");
    }
  };

  const handleIgnore = () => {
    setIgnored(true);
    try {
      localStorage.setItem(IGNORE_KEY, latest);
    } catch {
      // best-effort
    }
  };

  const pct =
    progress.total > 0
      ? Math.min(100, Math.round((progress.downloaded / progress.total) * 100))
      : null;

  return (
    <div style={styles.overlay}>
      <div className="animate-scale-in" style={styles.card}>
        {/* Header */}
        <div style={styles.header}>
          <div style={styles.iconCircle}>
            <span style={{ fontSize: 22 }}>✨</span>
          </div>
          <div style={styles.title}>MyShell 有新版本可用</div>
          <div style={styles.version}>{latestDisplay}</div>
        </div>

        {/* Subtitle / status */}
        <div style={styles.subtitle}>
          {phase === "prompt" &&
            (isBrowserMode
              ? "检测到新版本。当前系统暂不支持应用内自动更新，请前往下载页手动下载安装。"
              : "新版本已就绪，是否立即更新？")}
          {phase === "downloading" &&
            (pct !== null ? `正在下载… ${pct}%` : "正在下载…")}
          {phase === "ready" && "下载完成，点击安装并重启应用"}
          {phase === "failed" && (error || "下载出现问题")}
        </div>

        {/* Progress bar */}
        {phase === "downloading" && (
          <div style={styles.progressTrack}>
            <div
              style={{
                ...styles.progressFill,
                width: pct !== null ? `${pct}%` : "0%",
              }}
            />
          </div>
        )}

        {/* Actions */}
        <div style={styles.actions}>
          {phase === "prompt" && (
            <>
              <button
                onClick={handleIgnore}
                style={styles.btnGhost}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background =
                    "var(--bg-surface-hover)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = "transparent";
                }}
              >
                忽略
              </button>
              {isBrowserMode ? (
                <button
                  onClick={() =>
                    downloadUrl && openExternalUrl(downloadUrl)
                  }
                  style={styles.btnPrimary}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background =
                      "var(--accent-primary-hover)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background =
                      "var(--accent-primary)";
                  }}
                >
                  打开下载页
                </button>
              ) : (
                <button
                  onClick={handleUpdate}
                  style={styles.btnPrimary}
                  onMouseEnter={(e) => {
                    e.currentTarget.style.background =
                      "var(--accent-primary-hover)";
                  }}
                  onMouseLeave={(e) => {
                    e.currentTarget.style.background =
                      "var(--accent-primary)";
                  }}
                >
                  更新
                </button>
              )}
            </>
          )}
          {phase === "downloading" && (
            <div style={styles.downloadingText}>请稍候，下载完成后将自动提示…</div>
          )}
          {phase === "ready" && (
            <button
              onClick={handleInstall}
              style={{ ...styles.btnPrimary, width: "100%" }}
              onMouseEnter={(e) => {
                e.currentTarget.style.background =
                  "var(--accent-primary-hover)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.background = "var(--accent-primary)";
              }}
            >
              安装并重启
            </button>
          )}
          {phase === "failed" && (
            <>
              <button
                onClick={() => downloadUrl && openExternalUrl(downloadUrl)}
                style={styles.btnPrimary}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background =
                    "var(--accent-primary-hover)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background =
                    "var(--accent-primary)";
                }}
              >
                浏览器下载
              </button>
              <button
                onClick={handleUpdate}
                style={styles.btnGhost}
                onMouseEnter={(e) => {
                  e.currentTarget.style.background =
                    "var(--bg-surface-hover)";
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.background = "transparent";
                }}
              >
                重试
              </button>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// ─── Styles (Double-Bezel architecture + inline CSS vars) ────────────────

const styles: Record<string, React.CSSProperties> = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "var(--bg-overlay)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1500,
  },
  card: {
    width: 400,
    maxWidth: "90vw",
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-emphasis)",
    borderRadius: "var(--radius-xl)",
    boxShadow: "var(--shadow-xl)",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "28px 24px 0",
    gap: 10,
  },
  iconCircle: {
    width: 48,
    height: 48,
    borderRadius: "var(--radius-full)",
    background: "var(--accent-primary-muted, rgba(88,166,255,0.12))",
    border: "1px solid var(--border-subtle)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--accent-primary)",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.08)",
  },
  title: {
    fontSize: 17,
    fontWeight: 600,
    color: "var(--text-primary)",
    letterSpacing: "-0.01em",
  },
  version: {
    fontSize: 13,
    fontWeight: 500,
    color: "var(--accent-primary)",
    background: "var(--accent-primary-muted, rgba(88,166,255,0.12))",
    padding: "3px 12px",
    borderRadius: "var(--radius-full)",
    letterSpacing: "0.02em",
  },
  subtitle: {
    textAlign: "center" as const,
    fontSize: 13,
    color: "var(--text-tertiary)",
    lineHeight: 1.5,
    padding: "14px 24px 0",
  },
  progressTrack: {
    height: 3,
    background: "var(--bg-surface)",
    margin: "14px 24px 0",
    borderRadius: "var(--radius-full)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    background: "var(--accent-primary)",
    borderRadius: "var(--radius-full)",
    transition: "width 150ms cubic-bezier(0.32, 0.72, 0, 1)",
  },
  actions: {
    display: "flex",
    gap: 10,
    padding: "20px 24px 24px",
  },
  downloadingText: {
    flex: 1,
    textAlign: "center" as const,
    fontSize: 12,
    color: "var(--text-muted)",
    padding: "8px 0",
  },
  btnPrimary: {
    flex: 1,
    padding: "10px 20px",
    background: "var(--accent-primary)",
    color: "#ffffff",
    border: "none",
    borderRadius: "var(--radius-md)",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    transition: "background 200ms cubic-bezier(0.32, 0.72, 0, 1)",
    lineHeight: 1.4,
  },
  btnGhost: {
    flex: 1,
    padding: "10px 20px",
    background: "transparent",
    color: "var(--text-secondary)",
    border: "1px solid var(--border-default)",
    borderRadius: "var(--radius-md)",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    transition: "background 200ms cubic-bezier(0.32, 0.72, 0, 1)",
    lineHeight: 1.4,
  },
};
